name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  discover-projects:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker project matrix
        id: set
        run: |
          projects=$(find projects -mindepth 1 -maxdepth 1 -type d -exec test -f "{}/Dockerfile" \; -print | sed 's|projects/||' | jq -R . | jq -cs .)
          echo "matrix={\"project\":$projects}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: discover-projects
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-projects.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push for ${{ matrix.project }}
        run: |
          PROJECT=projects/${{ matrix.project }}
          NAME=${{ matrix.project }}
          TAG=${GITHUB_SHA::7}

          DOCKERHUB_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${NAME}:${TAG}
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/${NAME}:${TAG}

          echo "🛠 Building $NAME..."
          docker build -t $DOCKERHUB_IMAGE $PROJECT

          echo "🚀 Pushing to Docker Hub: $DOCKERHUB_IMAGE"
          docker push $DOCKERHUB_IMAGE

          echo "📦 Tagging and pushing to GHCR: $GHCR_IMAGE"
          docker tag $DOCKERHUB_IMAGE $GHCR_IMAGE
          docker push $GHCR_IMAGE

      - name: Optionally push latest tag
        if: github.ref == 'refs/heads/main'
        run: |
          LATEST_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.project }}:latest
          GHCR_LATEST=ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:latest

          docker tag $DOCKERHUB_IMAGE $LATEST_TAG
          docker push $LATEST_TAG

          docker tag $DOCKERHUB_IMAGE $GHCR_LATEST
          docker push $GHCR_LATEST
